export type ContentType = "Analysis" | "Perspective";
export type Audience = "Executive Leadership" | "HR & Talent" | "Hiring & Management";

export interface Article {
  /** kebab-case slug, used as both URL and React key */
  slug: string;
  title: string;
  dek: string;
  body: string[];
  type: ContentType;
  audience: Audience;
  /** ISO date (YYYY-MM-DD), used for JSON-LD and ordering */
  publishedAt: string;
}

export const articles: Article[] = [
  {
    slug: "cfo-seat-wont-stay-filled",
    title: "The CFO seat won't stay filled.",
    dek: "Finance chiefs are turning over at the fastest pace in two decades, and the bench underneath them is thinner than most boards believe.",
    type: "Analysis",
    audience: "Executive Leadership",
    publishedAt: "2026-02-04",
    body: [
      "The Crist Kolder Volatility Report has tracked Fortune 500 and S&P 500 CFO turnover every year since 2005. The 2024 reading came in at 18.5%, the highest rate they have ever recorded, and the 2025 update kept the number in that same elevated band. Average tenure is now hovering at roughly 4.7 years and falling. This is not a blip.",
      "Russell Reynolds' quarterly CFO Turnover Index has been telling the same story from a different vantage point: announced CFO departures across the S&P 500, FTSE 100, ASX 200, and CAC 40 hit multi-year highs through 2024 and have not meaningfully cooled. The pattern is consistent across geography and sector, which makes the usual explanations insufficient. One bad industry or one capital cycle does not account for it.",
      "What is actually going on is a compounding of four pressures the role was not designed to absorb at the same time. Capital costs reset and stayed reset. AI is rewriting the finance operating model on a quarter-by-quarter basis. Regulatory and disclosure regimes (climate, cyber, AI governance) have expanded the scope of the seat. And boards, post-2023, are using CFOs as the primary lever for cost discipline and operating restraint, which makes the role politically exposed in a way it was not a decade ago.",
      "The hidden problem is the bench. Deloitte's CFO Signals work and Korn Ferry's succession research have both flagged that internal CFO-ready successors are scarce. Most large companies have zero or one truly ready candidate, not the three or four that good succession planning assumes. When the seat opens, the search starts cold.",
      "For boards and CEOs, the implication is not 'hire faster.' It is to re-scope before sourcing. The CFO mandate you wrote in 2021 (capital allocation, IR fluency, ERP modernization) is not the mandate the next person will actually be asked to execute. Get the next 24 months of pressure honestly on paper before the search begins, or replace the outgoing CFO with a version of the outgoing CFO and start the cycle again in three years.",
      "There is also a fractional answer worth naming. For mid-market and PE-backed companies, the gap between a departing CFO and the right permanent successor is now routinely 6 to 9 months. A senior fractional or interim CFO during that window is not a stopgap. It is the difference between a clean handoff and a forced hire.",
    ],
  },
  {
    slug: "ai-replaced-the-shortlist",
    title: "AI didn't replace the recruiter. It replaced the shortlist.",
    dek: "What generative AI has actually changed inside senior hiring, and the new failure modes nobody is putting on a slide.",
    type: "Analysis",
    audience: "HR & Talent",
    publishedAt: "2026-01-28",
    body: [
      "LinkedIn's 2025 Future of Recruiting report found that 73% of talent acquisition professionals now consider AI a top priority and 37% are actively integrating it into sourcing and screening. SHRM's 2024 and 2025 data shows roughly one in four U.S. employers using AI somewhere in their hiring workflow, concentrated in sourcing, resume screening, and interview scheduling. The sourcing layer has effectively collapsed in cost and speed. That is the real change. Almost everything else being sold as 'AI in hiring' is downstream of it.",
      "For senior roles, the collapse cuts both ways. Identifying a long list of plausibly qualified candidates is now a commodity. So is writing an outreach sequence, drafting a job description, and producing a competency-mapped scorecard. The work that used to fill the first three weeks of a search now fills the first three days.",
      "The candidate side has moved at least as fast. Resume tailoring, interview prep, written assessments, and case responses are now AI-assisted by default at the senior level. A 2024 Gartner survey found 47% of candidates have already used AI to help with applications, and the figure climbs sharply among executives. Several large enterprises (Amazon, Anthropic, and a growing list of consultancies) have publicly restricted AI use during live interviews because it became impossible to assess the human underneath.",
      "Three failure modes are now showing up consistently in the searches we audit.",
      "First, synthetic candidates. Not just embellished resumes, but fully fabricated work histories, generated headshots, and AI-assisted live interviews using real-time prompting. The FBI and a stream of CISO reports through 2024 documented this at scale, originally tied to nation-state employment fraud, now spilling into ordinary white-collar roles. The defense is not a better ATS. It is structured reference work and verified credential checks, which most firms quietly stopped doing.",
      "Second, the shortlist that looks right and isn't. When sourcing is cheap, the bar for 'qualified enough to interview' silently drops. Hiring teams end up running more interviews against weaker slates and calling the noise 'optionality.' The fix is not more candidates. It is harder scope work before any name is surfaced.",
      "Third, the assessment that measures the model, not the person. AI-graded video interviews and AI-written case responses are now common enough that what you are scoring is often the candidate's tooling, not their judgment. For senior hires this is a category error.",
      "What the human work has to be now is narrower and harder: scope architecture, deep referencing through actual relationships, stakeholder choreography, and onboarding through day 90. None of that is automatable. All of it is what the fee was always supposed to be paying for.",
    ],
  },
  {
    slug: "fractional-is-no-longer-a-bridge",
    title: "Fractional is no longer a bridge.",
    dek: "The fractional executive market has crossed a line. For a growing share of mid-market and PE-backed companies, it is the operating model, not the gap before one.",
    type: "Analysis",
    audience: "Executive Leadership",
    publishedAt: "2026-01-21",
    body: [
      "The shift is most visible in three seats: CMO, CFO, and Chief People Officer. Industry trackers including Chief Outsiders and BTA's fractional executive surveys put the U.S. fractional executive population in the tens of thousands and growing at double-digit rates year over year. Harvard Business Review's 2024 coverage of the fractional C-suite framed it as a structural rather than cyclical shift, and the pattern through 2025 has confirmed that read.",
      "The reasons are not mysterious. Senior talent burned by 2022 and 2023 layoffs is unwilling to re-bet on a single employer. Companies between $10M and $150M in revenue cannot afford a full-time CXO at current comp benchmarks but cannot grow without that caliber of judgment. Capital constraints have made every full-time senior hire a 12-month commitment the CEO does not want to make until the motion is proven.",
      "What has changed in 2024 and 2025 is the engagement pattern. The early fractional market was time-boxed: three months, six months, a defined deliverable. The current market is closer to ongoing part-time leadership: two or three days a week, multi-year, fully integrated into the executive team. That is a different operating model, and it works when three conditions are true.",
      "One: the scope is permanent, but the volume is not. A 60-person company genuinely needs a Chief People Officer's judgment, not a CPO's full week. Two: the company has earned the right to a specific operator with a specific playbook, and that operator is not available full-time at any price. Three: the CEO is willing to treat the fractional executive as a peer, not a vendor, including in board materials and comp structure.",
      "There are also three situations where fractional is the wrong answer, and the market is selling it anyway. When the role requires deep cultural authorship, such as a founding CHRO during a values reset, a CRO building a sales org from zero, or a CTO inheriting a platform rebuild. When the company is in active crisis and needs daily presence. And when 'fractional' is being used to avoid the comp conversation a full-time hire would force. In each case, fractional buys time and defers a decision the company will eventually have to make under worse conditions.",
      "For VPs of HR and boards, the practical move is to stop treating fractional as a category and start treating it as a configuration. The question is not 'should we go fractional?' It is: 'what is the smallest senior intervention that gets us through the next four quarters, and at what point does that intervention need to become permanent?' Answer that honestly and the engagement shape writes itself.",
    ],
  },
  {
    slug: "return-to-office-retention",
    title: "The return-to-office fight is over. The retention fight isn't.",
    dek: "RTO mandates have largely landed. The senior attrition they triggered is the part most leadership teams are still under-counting.",
    type: "Analysis",
    audience: "HR & Talent",
    publishedAt: "2026-01-14",
    body: [
      "By mid-2025, Resume Builder's tracking showed roughly 9 in 10 companies that wanted employees back in the office had implemented a mandate, with full five-day-in-office requirements rising sharply through the year. KPMG's 2024 CEO Outlook found 83% of CEOs expected a full return within three years, and most are now executing on that view. The mandate fight is, functionally, over. What it produced is a quieter, more expensive problem.",
      "The data on senior-level attrition tied to RTO is now solid enough to take seriously. A widely-cited University of Pittsburgh and Baylor study of S&P 500 firms found that companies implementing strict RTO mandates experienced significantly higher turnover among senior, longer-tenured, and higher-skilled employees, and notably slower backfilling. Gartner's 2024 research put the threatened attrition rate at around 35% among high-performers in companies with full-time office mandates. Gallup's State of the Global Workplace shows employee engagement at a decade low, with managers (the layer that actually holds the operating model together) hit hardest.",
      "The piece most HR leaders are still mis-reading is which leaders leave and why. The departures rarely cite the mandate directly. They cite the rollout: surprise announcements, exceptions granted to favored executives, inconsistent enforcement, the suspicion that the policy was about headcount reduction without saying so. Senior people read those signals quickly and start taking calls.",
      "There is also a recruiting consequence the slide decks do not capture. The senior talent pool has effectively bifurcated. A meaningful share of the most experienced operators, particularly in finance, engineering leadership, and product, will not engage with a five-day-in-office search at any comp level. That has not closed the market, but it has narrowed it, and the narrowing is concentrated in the seats most boards care about most.",
      "What VPs of HR should actually be doing in 2026 is three things. First, run a private attrition risk read on your top two layers of leadership specifically against the rollout, not the policy. Who watched it happen and quietly downgraded their commitment? Second, separate the policy from the messaging. Most of the damage is repairable through how the next twelve months are managed, not through reversing the mandate. Third, get honest about which roles you are willing to lose the best candidate for in order to hold the line on attendance. That is a defensible answer. 'We didn't realize we were making that trade' is not.",
    ],
  },
  {
    slug: "boutique-vs-brand-name-search",
    title: "Why the next search you run should not go to a brand-name firm.",
    dek: "The structural advantages of boutique executive search compounded through 2024 and 2025. Going into 2026, the math on the global firms has stopped working for most mid-market and PE-backed mandates.",
    type: "Analysis",
    audience: "Executive Leadership",
    publishedAt: "2026-01-07",
    body: [
      "Hunt Scanlon's 2025 market data shows the boutique and specialized segment of executive search continuing to take share from the global brands for the fifth consecutive year. AESC's own membership reporting tells the same story from inside the industry: the fastest growth is at firms under 50 consultants, not at the names every board still defaults to. There is a structural reason for it, and most search committees only discover it after the second failed engagement.",
      "Start with off-limits. The global firms run a placement volume that mathematically blocks them from recruiting at the companies they serve. A firm that places hundreds of executives a year across the Fortune 1000 cannot touch any of those companies' talent for 12 to 24 months under standard off-limits clauses. By 2025, that effectively removed a meaningful slice of the senior talent universe from those firms' addressable pool. Boards rarely ask the question on the front end. They feel it on the back end when the shortlist is thinner than the brand suggested.",
      "Then there is who actually runs the search. The pitch is delivered by a name partner. The work is done by an associate two years out of business school. That model is not a secret anymore, and in 2025 it became one of the standard RFP questions: who specifically will be on the phone with candidates, and what is their average tenure in the seat we are filling? Boutique firms answer that question with the same person who sold the engagement. The global firms answer it with an org chart.",
      "Process is the third issue. At scale, search becomes a manufactured product: a standardized scorecard, a templated competency model, a pipeline report that looks the same whether the role is a divisional CFO at a $2B company or a Chief People Officer at a $200M one. That sameness is what scale requires. It is also what flattens the judgment that a senior hire is actually buying.",
      "The cost argument has flipped too. Once you normalize for the retainer plus the third-installment fee plus the off-limits ripple cost (the talent you can no longer recruit at the firms that referred you in), boutique engagements are routinely 20 to 30 percent less expensive end-to-end on a comparable senior search. The reason large firms have held the premium this long is brand insurance for the search committee, not better outcomes.",
      "Where the global firms still win, and where boards should still use them, is genuinely cross-border CEO and board-level work where global insurance and a published methodology matter to a regulator, an activist investor, or a foreign listing. For everything else (CFO, CHRO, CRO, divisional president, key VP), the boutique math has been clearer than the brand math for at least two years now, and 2026 is the year search committees should stop defaulting and start choosing.",
    ],
  },
  {
    slug: "senior-time-to-hire-94-days",
    title: "Hiring a senior leader in 2026 takes 94 days. Most of that is not searching.",
    dek: "Time-to-hire for senior roles has not improved despite AI sourcing. The bottleneck moved. The companies shortening the cycle are doing specific things, and almost none of it has to do with technology.",
    type: "Analysis",
    audience: "Hiring & Management",
    publishedAt: "2025-12-17",
    body: [
      "LinkedIn's 2025 Talent Trends and Workable's benchmark data both put median time-to-fill for senior and executive roles in the 80 to 100 day range, and rising. AI has compressed the sourcing layer by an order of magnitude, but total cycle time has barely moved. That is the paradox everyone in talent acquisition is quietly grappling with. The bottleneck is not finding people. It has not been finding people for two years.",
      "Four things actually consume the calendar.",
      "Scope iteration is the first and largest. A 2025 Gartner study of executive searches found the average senior role had its scorecard materially revised at least twice between kickoff and offer, usually after the first round of interviews surfaced something the hiring team had not articulated. Every revision resets the funnel. The fix is not faster sourcing. It is harder scope work before the first conversation, including the uncomfortable question of what the company is actually trying to buy that it does not currently have.",
      "Interview choreography is the second. Senior hires now routinely involve seven to nine decision-makers across distributed time zones, and the calendar math alone adds two to three weeks. The companies shortening this are not running more interviews. They are running fewer, longer, better-prepared ones, and they are giving one person (usually the hiring manager, occasionally the CEO) the authority to call the slate done when it is done.",
      "Compensation negotiation is the third, and 2025 made it materially harder. Comp benchmarks reset twice during the year in several functions (AI engineering leadership and senior finance especially), and candidates with active offers have leverage they did not have in 2022. The companies that close cleanly do their own comp work up front rather than discovering the market through three rounds of counteroffer.",
      "Reference and credential verification is the fourth, and the time spent here has roughly doubled since 2023. The synthetic-candidate problem (documented by the FBI through 2024 and now extending well beyond nation-state cases) means every senior hire warrants structured back-channel referencing and verified credentials, not the perfunctory two-call ritual most firms reverted to during the 2021 talent crunch.",
      "There is also a 2025 phenomenon worth naming: second-offer attrition. A meaningful share of senior hires made during long cycles in 2024 and 2025 resigned inside 90 days because comp moved during the search and a better offer landed after acceptance. The cycle did not just take longer. It cost more, twice.",
      "The practical move for VPs of HR going into 2026 is to stop measuring time-to-hire as one number and start measuring it in four: scope-to-slate, slate-to-final, final-to-offer, and offer-to-day-90 retention. The total only matters if the last number holds.",
    ],
  },
  {
    slug: "statement-of-work-engagement-model",
    title: "Statement of work is the engagement model nobody is asking for, and most companies need.",
    dek: "Retained search and fractional leadership are not the only two shapes a senior talent engagement can take. For a specific class of problem, a defined-scope SOW is the right answer, and almost no firm offers it because it caps revenue.",
    type: "Analysis",
    audience: "Executive Leadership",
    publishedAt: "2025-12-10",
    body: [
      "Procurement has spent the last three years pushing every category of advisory spend (legal, consulting, technology, and now talent) toward defined-scope, fixed-fee engagements. The pattern is clearest at PE-backed and mid-market companies, where open-ended retainers no longer survive a portfolio review. Talent advisory is the last category to feel it, and 2026 is the year the question gets asked at most search RFP meetings: can we do this as an SOW instead?",
      "The short answer is yes, for a specific class of problem, and most firms will not offer it because the model caps revenue. A retained search bills as a percentage of comp regardless of how hard the work actually was. An SOW bills for the scope you actually agreed to. The economics favor the buyer when the scope is well-defined and the firm when the scope is genuinely ambiguous. Honest firms tell you which one you have before quoting.",
      "Five engagement shapes work cleanly as SOW.",
      "One: a single named VP or director search bundled with structured onboarding through day 90, fixed fee, defined deliverable. The fee is typically lower than a comparable retained search and the firm carries onboarding accountability the retained model does not.",
      "Two: a leadership team assessment. Three to six executives, a defined methodology, a written read on bench strength and succession risk, delivered in 60 days. Most boards have never commissioned one because no firm in their rolodex sells it as a discrete product.",
      "Three: a compensation framework rebuild for the top two layers. Benchmark, leveling, equity philosophy, a board-ready document. Eight to twelve weeks, fixed price.",
      "Four: a succession plan for the executive team. Internal candidate identification, gap analysis, development paths for the ready-in-two-years cohort, and a documented external bench for the seats where no internal candidate exists.",
      "Five: a search audit. An independent read on a failed or stalled engagement (whether the firm is yours or someone else's), including what the scope missed, what the slate lacked, and what to do next. This is the engagement most companies wish they had run before starting search number two.",
      "Where SOW is the wrong shape: any engagement where the scope genuinely cannot be defined up front (a CEO search at a company in transition, a build from zero of a function the company has never had), and any engagement where the value is in the ongoing relationship rather than a discrete deliverable (an embedded fractional CHRO, a multi-quarter advisory seat).",
      "For VPs of HR and CFOs sitting on advisory budgets in 2026, the practical move is to stop asking 'retained or fractional?' and start asking 'what is the smallest, cleanest scope of work that gets us the outcome we actually need?' For a meaningful share of senior talent problems, the honest answer is an SOW that no one has offered you yet.",
    ],
  },
  {
    slug: "end-of-keyword-search",
    title: "The end of keyword search.",
    dek: "Why committed executive search has to re-earn its premium, and what that actually looks like in practice.",
    type: "Perspective",
    audience: "Executive Leadership",
    publishedAt: "2025-12-03",
    body: [
      "A lot of what is sold as committed or strategic executive search today is a sourcing motion dressed up in advisory language. A database query, a partner-fronted pitch, and a junior team running the actual work behind the curtain. It is worth naming, because plenty of firms still do the work the right way and they are getting confused with the firms that do not.",
      "Boards are starting to notice. The premium fee survived as long as two assumptions held: that the firm's network was meaningfully closed, and that its judgment was meaningfully experienced. Both assumptions are now testable. LinkedIn made the first one transparent. AI sourcing tools made the second one auditable. A fair number of firms struggle with the test.",
      "The work that justifies the fee is not the sourcing. It is the scope architecture at intake, the deep referencing through actual relationships rather than supplied lists, the candid read on candidates the client likes for the wrong reasons, and the stakeholder choreography around a difficult hire. That work is harder to scale, harder to package, and harder to delegate to a 26-year-old associate. Which is exactly why it is what you are paying for.",
      "The firms that will keep commanding the premium over the next five years are the ones willing to be smaller on purpose. They will run fewer searches per partner, they will turn down assignments that do not fit, and they will be in the room for the parts of the process that matter rather than handing those off the moment the engagement letter signs.",
      "If you are a board member or a CEO buying executive search right now, the diligence question is no longer 'what is your network?' Every credible firm has a comparable surface network. The question is 'who, by name, is doing the work on my search after week two, and how much of their time am I getting?' If the answer is vague, you already have your answer.",
    ],
  },
  {
    slug: "fractional-full-time-or-none",
    title: "Fractional, full-time, or none of the above.",
    dek: "A decision framework for founders weighing senior leadership hires against runway, stage, and the work that actually needs to happen.",
    type: "Perspective",
    audience: "Executive Leadership",
    publishedAt: "2025-11-26",
    body: [
      "The default question, 'should we hire a CRO?', is almost always the wrong starting point. The right question is, 'what does the next twelve months of revenue motion need to look like, and what is the smallest senior intervention that gets us there?' The framing matters because the default question forces a binary answer, and the binary is wrong roughly half the time.",
      "Fractional makes sense in three patterns. When the runway cannot yet carry a full-time CXO at market comp. When the company needs a specific operator's playbook for a defined window, such as a pricing reset, a GTM redesign, or a finance function rebuild. And when the role is real but the underlying motion is not yet validated, meaning a full-time hire would be optimizing a system that is still being designed.",
      "Full-time makes sense when three different conditions hold. The work is permanent, not project-shaped. The comp is supportable on the current plan without forcing a round. And the company has earned the right to a specific person who will not work fractionally at any price. The third condition is the one most founders skip, and it is the one that determines whether the search is realistic or aspirational.",
      "There is a third answer that more founders should consider than do: none of the above. Sometimes the honest read is that the company does not need a CXO yet. It needs a senior individual contributor, or a strong director, or a few months of advisory time from someone who has run the function before. Hiring a CXO into a company that is not ready for one is one of the most expensive mistakes a founder can make, because the wrong senior hire takes 12 to 18 months to unwind and costs the company momentum it may not get back.",
      "The discipline is to separate the work from the title. Write down the four or five outcomes that have to be true twelve months from now. Then ask which configuration of human time, at what seniority, actually delivers those outcomes. The title falls out of that conversation. It should not lead it.",
    ],
  },
  {
    slug: "onboarding-is-the-search",
    title: "Onboarding is the search.",
    dek: "Why the first ninety days inside the role decide whether a placement is a hire or a write-off, and what changes when the firm stays in the room.",
    type: "Perspective",
    audience: "Hiring & Management",
    publishedAt: "2025-11-19",
    body: [
      "Most firms quietly treat the offer letter as the finish line. The placement is announced, the fee invoices, and the firm disappears. Eighteen months later, the placement leaves and no one is sure why. The firm's reporting will record the search as successful, because the metric the firm tracks ends at start date.",
      "The honest answer, most of the time, is that onboarding was not part of the engagement. Scope was right, sourcing was right, the candidate was right, and then the company handed them a laptop and a Slack invitation and called it integration. Senior leaders fail in the first year for predictable reasons: an unspoken disagreement with the CEO about scope, a peer relationship that was never reset after their arrival, or a board member with a private mandate the new hire never heard about.",
      "The hire is finished at day ninety, not at day one. Structured 30, 60, and 90-day check-ins, run with both the placement and the hiring executive, surface the issues that destroy placements before they become unrecoverable. The conversations are short, they are uncomfortable on purpose, and they are the cheapest insurance the engagement can buy.",
      "The check-ins also keep the firm honest about the work it actually did. If a placement is struggling at day 60 because the role was mis-scoped at intake, that is information the firm should have to sit with. The firms that are willing to be present for that conversation are the firms that learn. The firms that disappear at start date keep making the same mistakes on behalf of the next client.",
      "For the company, the practical move is to write onboarding accountability into the engagement letter before signing. Define the check-in cadence, the participants, and what happens if the relationship is in trouble at day 90. A firm that resists those terms is telling you, in writing, where their work stops. Pay attention to that.",
    ],
  },
  {
    slug: "scope-before-sourcing",
    title: "Scope before sourcing.",
    dek: "The single most common reason senior searches fail, and the one conversation that prevents it.",
    type: "Perspective",
    audience: "Hiring & Management",
    publishedAt: "2025-11-12",
    body: [
      "We have done the post-mortem on dozens of failed senior searches over the years, our own and others'. The same pattern shows up almost every time. The role was mis-scoped at intake, and no one re-wrote it before sourcing began. Everything downstream then optimized against the wrong target.",
      "Mis-scoped means the job description is a wishlist of every quality the leadership team admires, rather than a structured statement of the outcomes the leader must own and the constraints they must operate within. The shortlist that follows is unfocused. The interviews are exploratory rather than evaluative. The offer, when it comes, is a compromise that nobody in the room will defend out loud.",
      "The conversation that prevents this is uncomfortable. It involves telling a CEO that the role they have written cannot be filled by a single human, or that two of the listed requirements contradict each other, or that the comp band they have approved does not match the market for what they are actually asking for. It is also, almost always, the most valuable hour of the engagement.",
      "The output of that hour is a one-page scope document that the entire interviewing team agrees to before the first candidate is contacted. Three to five outcomes the leader must produce in the first twelve months. The two or three constraints that make the role unusually hard. The non-negotiables and, more importantly, the requirements that look non-negotiable but are not. That page becomes the rubric for every interview, every reference, and every offer conversation.",
      "Companies that do this work upfront close searches faster, with cleaner offers, and with hires that survive past the eighteen-month mark. Companies that skip it pay for the same search twice. The math on that is not subtle, and yet the temptation to start sourcing on day one, before the scope is honest, is the single hardest discipline to hold in this business.",
    ],
  },
  {
    slug: "hiring-through-a-capital-event",
    title: "Hiring through a capital event.",
    dek: "What changes about senior hiring when the cap table changes, and how to build the team the next round actually needs.",
    type: "Perspective",
    audience: "Executive Leadership",
    publishedAt: "2025-11-05",
    body: [
      "The team that got the company to a Series B is rarely the team that takes it to a Series D. This is not a criticism of the original team. It is a statement about scope. Different stages require different operators, and the most common failure mode is hiring the previous stage's team again, one round late.",
      "A capital event is also a forcing function for honesty. The diligence the lead investor runs on the team is, in effect, a third-party scope audit. Companies that have been deferring leadership decisions for two quarters often have those decisions made for them at the term sheet, in the form of a board-mandated CFO search or a CRO replacement written into the closing conditions.",
      "The work begins six months before the round, not six months after. By the time the wire hits, the senior plan should already be on paper. The named-target list for the priority seats should already be sourced. The first conversations, framed as exploratory, should already be underway. Founders who wait until after close to start the searches lose the first six to nine months of the new capital to recruiting cycles, and the round runs out faster than the model said it would.",
      "There is a second-order effect worth naming. The senior people you can hire in the four weeks after a round announces are not the same people you can hire in the four months before. Public capital events compress the market. Every search firm in town knows the company just raised, every passive candidate gets ten inbounds the same week, and the negotiating leverage shifts hard toward the candidate. The companies that recruit ahead of the announcement get materially better outcomes.",
      "The discipline is to treat the round and the team as one plan, not two. The pitch the founder takes to the board for the round should include the leadership map for the twelve months after close, with names, sequence, and expected cost. If that map does not exist when the term sheet arrives, the round is, in a real sense, only half-prepared.",
    ],
  },
  {
    slug: "career-capital",
    title: "Career capital.",
    dek: "Why the most consequential moves in a senior career should be planned years before they are made.",
    type: "Perspective",
    audience: "Executive Leadership",
    publishedAt: "2025-10-29",
    body: [
      "Senior careers compound. The next role is recruited from the last role. The next board seat is offered to the operator who has been visibly board-ready for eighteen months. The next exit option is structured by the choices made three roles ago. None of this is accidental, and very little of it is improvised at the moment of decision.",
      "Most senior leaders, however, treat career decisions reactively. They evaluate inbound conversations as they arrive, rather than constructing a deliberate portfolio of positioning, relationships, and target experiences. The market does not reward this. The leaders who land the consequential roles, and the consequential boards, have been building toward them for years in ways that look like luck from the outside.",
      "Career advisory at this level is the work of building the position before it is needed. Positioning means having a sharp, defensible answer to 'what kind of operator are you?' that is consistent across your public surface, your private references, and the way recruiters describe you when you are not in the room. Narrative means knowing which one or two stories from the last role you want to be known for, and making sure those stories actually reach the people who matter for the next role.",
      "Network means building, before you need them, the dozen or so relationships that will surface the consequential opportunities. Those relationships are not LinkedIn connections. They are senior operators, two or three search partners with real reach in your sector, and a small number of board members and investors who would take a call on you without thinking about it. None of that gets built in a quarter.",
      "Target landscape means knowing, with specificity, the twenty or thirty roles that would be the right next move and the conditions under which each of them is likely to open. That list is updated quarterly, quietly, in the background. When one of them opens, you are not starting from scratch. You are activating six to twenty-four months of preparation.",
      "The leaders who do this work look, from the outside, like they are perpetually being offered the right thing at the right time. They are not. They are running a process. The earlier in a senior career that process starts, the more consequential the eventual moves become.",
    ],
  },
  {
    slug: "the-disappearing-entry-level-job",
    title: "The disappearing entry-level job.",
    dek: "Other technologies reshaped hiring at the edges. Generative AI is quietly cutting the first rung off the ladder, and the early data is no longer ambiguous.",
    type: "Perspective",
    audience: "Hiring & Management",
    publishedAt: "2026-06-01",
    body: [
      "Every meaningful workplace technology of the last forty years changed who got hired and on what terms. The PC in the 1990s killed the dedicated typing pool and the junior bookkeeper, and it created a generation of analysts who lived in Excel. ERP systems in the early 2000s consolidated half a dozen back-office coordinator roles into a smaller number of systems-literate generalists. Offshoring in the 2000s and 2010s moved entire tiers of contact center, QA, and basic accounting work out of the U.S. entirely. Cloud and SaaS in the 2010s made the junior sysadmin and the junior DBA largely unnecessary. Each of these was disruptive. None of them moved as fast, or cut as deep into the first rung of the career ladder, as what generative AI has done in the last four years.",
      "The pattern this time is different in two ways that matter. First, the speed. ChatGPT crossed 100 million users in two months at the start of 2023. By the end of 2025, generative AI was embedded inside the daily tooling of legal, finance, marketing, software engineering, customer support, and consulting at most large U.S. employers. No prior workplace technology compressed adoption that tightly. Second, the target. Earlier waves automated tasks at the edges of a role, or moved work geographically. Generative AI is automating the specific bundle of tasks that have historically defined entry-level white-collar work: drafting, summarizing, first-pass research, basic code, formatting, reconciliation, and the kind of structured output a manager used to assign to a 23-year-old to develop their judgment.",
      "The data has caught up to what hiring managers have been feeling. The Stanford Digital Economy Lab's November 2025 working paper, 'Canaries in the Coal Mine,' used ADP payroll data and found that workers aged 22 to 25 in AI-exposed occupations experienced a 16% relative decline in employment after the widespread adoption of generative AI, while older workers in the same firms and same occupations held steady or grew. The bottom rung is being removed in the roles where AI does the entry-level work, not the whole workforce. CNBC and PBS NewsHour both ran extended pieces through 2025 documenting the same pattern from the candidate side: the class of 2025 is facing one of the most difficult entry-level markets in a decade, and the class of 2026 is on track to face a harder one.",
      "MIT Technology Review's May 2026 piece, 'It's time to address the looming crisis in entry-level work,' put the structural point cleanly: aggregate employment looks stable, but the first rung of the career ladder is quietly weakening. That is the part that should worry every executive team. A workforce that does not hire and develop juniors today does not have mid-level operators in three years, and does not have a leadership bench in eight.",
      "What we are seeing in our own search work tracks the data. Three patterns now show up consistently inside our clients.",
      "First, the analyst layer is hollowing out. The associate, the analyst, the junior consultant, the entry-level marketing coordinator, the support engineer: the seats that used to absorb new graduates and convert them into operators over two or three years are being quietly held open, downsized, or replaced with a smaller number of mid-level hires who arrive AI-fluent. The companies doing this are reporting short-term productivity gains. They are also building, on a two-year delay, an unfillable gap at the senior associate and manager level.",
      "Second, the bar to be considered junior has moved. 'Entry-level' job descriptions in 2026 routinely ask for two to four years of experience, demonstrated AI fluency, and the ability to operate at a level that would have been called mid-level in 2021. The functional effect is that there is no true entry-level posting in many functions anymore. There is only a faster, harder mid-level pipeline that new graduates cannot enter without doing the development work themselves before they apply.",
      "Third, the development model that the seat used to provide is gone. The traditional path was: do the unglamorous junior work for two years, build judgment by repetition, then earn the next title. When AI does the unglamorous junior work, the repetitions never happen, and judgment does not develop. Companies are now starting to recognize that they have to engineer development deliberately, in a way that the old org chart used to do for free. Most have not done it yet.",
      "The honest perspective is this. Generative AI is not the first technology to disrupt hiring, but it is the first one to attack the specific layer of the workforce that we have always relied on to produce our future leaders. If executive teams treat that as a short-term cost-saving opportunity rather than a structural talent risk, the bill comes due quietly, in the form of a mid-level vacuum, in 2028 and 2029. The companies that will look most prescient in five years are the ones that are, right now, deliberately preserving and redesigning the first rung, even when the spreadsheet does not require them to.",
      "For boards and CEOs, the practical move is not to freeze entry-level hiring and call it efficiency. It is to ask, for each function, two questions. What is the work that AI is actually doing well today, and what is the work that a junior used to do that we still need a human to learn by doing? The answer to the second question is the job description for your next entry-level hire. It will not look like the one you posted in 2021. It should not.",
      "References: Brynjolfsson, Chandar, and Chen, 'Canaries in the Coal Mine? Six Facts about the Recent Employment Effects of Artificial Intelligence,' Stanford Digital Economy Lab working paper, November 2025. MIT Technology Review, 'It's time to address the looming crisis in entry-level work,' May 2026. CNBC, 'AI puts the squeeze on new grads looking for work,' November 2025. Fortune, 'First-of-its-kind Stanford study says AI is starting to have a significant and disproportionate impact on entry-level workers in the U.S.,' August 2025. PBS NewsHour, 'How AI may be robbing new college graduates of traditional entry-level jobs,' June 2025.",
    ],
  },
  {
    slug: "internship-is-the-new-entry-point",
    title: "The internship is the new entry point. Most students don't know how to get in the door.",
    dek: "The application volume has doubled. The postings have declined. And the students who are landing the right internships aren't just more qualified — they showed up before the posting existed.",
    type: "Perspective",
    audience: "Hiring & Management",
    publishedAt: "2026-06-10",
    body: [
      "Getting an internship used to be a numbers game. Send enough applications, show up reasonably prepared, and the odds would eventually work in your favor. That model is gone. The math has inverted, and most students and most parents have not caught up to what the market actually looks like right now.",
      "The data is unambiguous. Handshake reported an average of 109 applications per internship posting in 2025, nearly double from the prior year. In technology, that number was 273 applications per posting. In finance, 192. At the same time, job postings on Handshake declined 15% from the prior year. More students competing for fewer spots, in the same cycle, with the same generic resume and the same cover letter everyone else wrote. The volume strategy does not work when the volume is already working against you.",
      "The internship now functions as the real entry point into a career — not a nice credential to have, but the threshold requirement. Roughly four-fifths of college graduates who worked during school got hired soon after graduating, according to ZipRecruiter's estimate, compared to only about 41% of those who graduated with no work experience. That gap is not a rounding error. It is the difference between launching a career and spending the first two years after graduation trying to explain why you have not launched one yet.",
      "The pressure on that first internship is now acute enough that it is reshaping the full-time job market below it. Cengage reported that only 41% of 2024 graduates and only 30% of 2025 graduates found full-time jobs related to what they studied. The students who are breaking that pattern — landing selective internships, converting them to offers, graduating into roles with real trajectory — are not uniformly the most credentialed. They are the most prepared, in a specific way that most schools do not teach and most students do not figure out until it is too late.",
      "What we see consistently, across the students who land the right internship and the ones who do not, is not a gap in GPA or a gap in major. It is a gap in professional presence and outreach instinct, built months before recruiting season opens, not during it.",
      "Three patterns show up on the losing side of that gap, over and over.",
      "The first is an invisible profile. A LinkedIn page with a headshot and a class year is not a profile. It is a placeholder. LinkedIn's algorithm prioritizes semantic relevance, looking for skill clusters across a student's headline, about section, and experience, not just a job title in the bio. A recruiter running a search for a summer finance analyst intern does not find the student with the incomplete profile. They find the one who built theirs to be found. Most students have not done that work, and no one has shown them how.",
      "The second is late entry. Technology, finance, consulting, and Fortune 500 summer internship programs open recruiting as early as August and run through October for the following summer. The student who starts thinking about internships in February is not late by a few weeks. They are out of the cycle entirely for the most competitive programs. By the time they apply, those seats are filled or nearly filled, and what remains are the roles no one else took.",
      "The third is the application-only approach. Submitting through a portal is how most students engage with the process, and it is the least effective method available. LinkedIn's own data shows 64% of job seekers get hired through a referral. The students who land selective internships are not, as a rule, the ones who clicked Apply on 200 postings. They are the ones who identified the right decision-makers, built a real connection before a role was posted, and were already on someone's radar when the hiring conversation started. That is a skill. It is learnable. Most students have never been taught it.",
      "The honest read on where the internship market sits in 2026 is this: the competition has gotten structurally harder at the same time that the tools to stand out have gotten more accessible, if you know how to use them. The institutions producing students who consistently land the right roles are doing specific things: building AI fluency into the curriculum early, using resume and LinkedIn feedback tools proactively, and running structured interview preparation long before recruiting season. Those students are not smarter. They are better prepared, earlier.",
      "For the student who has not had that institutional advantage, which is most students, the preparation has to be built deliberately, outside the classroom, and it has to start before junior year if the goal is a selective summer internship in finance, technology, or operations. The recruiting cycle for those programs does not wait for a student to feel ready.",
      "The first move is not the application. It is the preparation that makes the application irrelevant, because by the time the role posts, the right people already know who you are.",
      "References: Handshake, internship application volume data, 2025. CNN Business, \"The job market is so tough, young people are struggling just to land internships,\" April 2026. College Recruiter, \"The entry-level job market is broken,\" May 2026. ZipRecruiter, graduate employment data, 2025. The Chronicle of Higher Education, \"The Entry-Level Job Market Stinks. These Grads Are Crushing It,\" March 2026. Cengage, graduate employment outcomes data, 2025. LinkedIn, referral hiring data, 2025. NACE, Job Outlook 2026 and 2026 Internship & Co-op Report.",
    ],
  },
];


export const SITE_URL = "https://prohireresources.com";

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
